import type { Briefing, TrendingStock } from "@/lib/types";

function pad2(n: number) {
  return String(n).padStart(2, "0");
}

export function formatDateYYYYMMDD(d: Date) {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

export function makeBriefingCoverSvgDataUrl(opts: {
  title: string;
  subtitle: string;
  accent: "green" | "red";
}) {
  const accent = opts.accent === "green" ? "#22c55e" : "#ef4444";
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#0b0f1a"/>
      <stop offset="60%" stop-color="#111b33"/>
      <stop offset="100%" stop-color="${accent}"/>
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="10" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <rect width="1080" height="1350" fill="url(#bg)"/>
  <circle cx="900" cy="220" r="160" fill="${accent}" opacity="0.20"/>
  <circle cx="180" cy="1130" r="220" fill="#ff2bd6" opacity="0.10"/>
  <text x="86" y="170" fill="#ffffff" font-size="42" font-family="Arial, Helvetica, sans-serif" opacity="0.85">While You Were Sleeping</text>
  <text x="86" y="300" fill="#ffffff" font-size="78" font-weight="700" font-family="Arial, Helvetica, sans-serif" filter="url(#glow)">${escapeXml(opts.title)}</text>
  <text x="86" y="380" fill="#dbeafe" font-size="40" font-family="Arial, Helvetica, sans-serif" opacity="0.9">${escapeXml(opts.subtitle)}</text>
  <rect x="86" y="460" width="908" height="2" fill="#ffffff" opacity="0.20"/>
  <text x="86" y="540" fill="#ffffff" font-size="40" font-weight="700" font-family="Arial, Helvetica, sans-serif">핵심 3줄</text>
  <text x="86" y="610" fill="#e5e7eb" font-size="34" font-family="Arial, Helvetica, sans-serif">• 거래량/상승률 기반 화제 종목 자동 선정</text>
  <text x="86" y="670" fill="#e5e7eb" font-size="34" font-family="Arial, Helvetica, sans-serif">• 관련 뉴스 요약 + 이유 한 줄</text>
  <text x="86" y="730" fill="#e5e7eb" font-size="34" font-family="Arial, Helvetica, sans-serif">• 이메일/슬랙 자동 발송</text>
  <g opacity="0.85">
    <text x="86" y="1220" fill="#ffffff" font-size="30" font-family="Arial, Helvetica, sans-serif">Generated by WYWS • mock</text>
  </g>
</svg>`;
  // data URL로 안전하게 넣기 위해 최소한의 인코딩만 수행
  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

function escapeXml(s: string) {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

export function getMockTrending(): { date: string; top1: TrendingStock; items: TrendingStock[] } {
  const date = formatDateYYYYMMDD(new Date());
  const items: TrendingStock[] = [
    {
      symbol: "TSLA",
      shortName: "Tesla, Inc.",
      quoteType: "EQUITY",
      regularMarketPrice: 248.12,
      regularMarketChangePercent: 8.34,
      regularMarketVolume: 195_004_321,
      sourceTags: ["most_actives", "day_gainers"],
      rank: { most_actives: 1, day_gainers: 4 },
      score: 0.91,
      selectedReason: "거래량 1위 + 상승률 상위 중복",
    },
    {
      symbol: "NVDA",
      shortName: "NVIDIA Corporation",
      quoteType: "EQUITY",
      regularMarketPrice: 139.5,
      regularMarketChangePercent: -3.02,
      regularMarketVolume: 131_100_120,
      sourceTags: ["most_actives", "day_losers"],
      rank: { most_actives: 3, day_losers: 6 },
      score: 0.62,
    },
    {
      symbol: "AAPL",
      shortName: "Apple Inc.",
      quoteType: "EQUITY",
      regularMarketPrice: 228.2,
      regularMarketChangePercent: 1.12,
      regularMarketVolume: 88_500_450,
      sourceTags: ["most_actives"],
      rank: { most_actives: 7 },
      score: 0.38,
    },
  ];

  return { date, top1: items[0], items };
}

export function getMockBriefings(): Briefing[] {
  const now = new Date();
  const today = formatDateYYYYMMDD(now);
  const yesterday = formatDateYYYYMMDD(new Date(now.getTime() - 24 * 60 * 60 * 1000));

  const b1: Briefing = {
    id: "brf_mock_today",
    date: today,
    title: `당신이 잠든 사이 — ${today} 브리핑`,
    status: "READY",
    top1Symbol: "TSLA",
    criteriaLabel: "거래량 1위 + 상승률 상위 중복",
    summaryText: "테슬라 급등이 시장 분위기를 끌어올렸고, 반도체는 변동성이 컸습니다.",
    reportText:
      "1) 오늘의 화제 종목: TSLA\n- 거래량 급증 + 상승률 상위 중복\n- 이슈: 전망 상향/수요 기대\n\n2) 체크포인트\n- 장 마감 후 실적/가이던스 발표 일정 확인\n- 변동성 확대 구간에서는 손절/분할매수 원칙 유지",
    imageDataUrl: makeBriefingCoverSvgDataUrl({
      title: "오늘의 브리핑",
      subtitle: `${today} • TOP1: TSLA`,
      accent: "green",
    }),
    createdAt: new Date(now.getTime() - 8 * 60 * 1000).toISOString(),
  };

  const b2: Briefing = {
    id: "brf_mock_yesterday",
    date: yesterday,
    title: `당신이 잠든 사이 — ${yesterday} 브리핑`,
    status: "READY",
    top1Symbol: "NVDA",
    criteriaLabel: "거래량 상위 + 하락률 상위 (변동성)",
    summaryText: "반도체 섹터 조정이 컸고, 일부 대형주는 횡보했습니다.",
    reportText:
      "1) 오늘의 화제 종목: NVDA\n- 거래량 상위 + 하락률 상위\n- 이슈: 금리/밸류에이션 민감\n\n2) 체크포인트\n- 매크로 지표 발표 전후 변동성 주의\n- 섹터 로테이션 신호 관찰",
    imageDataUrl: makeBriefingCoverSvgDataUrl({
      title: "어제의 브리핑",
      subtitle: `${yesterday} • TOP1: NVDA`,
      accent: "red",
    }),
    createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000 - 12 * 60 * 1000).toISOString(),
  };

  return [b1, b2];
}

export function makeNewMockBriefing(seed?: Partial<Pick<Briefing, "top1Symbol" | "criteriaLabel">>): Briefing {
  const now = new Date();
  const date = formatDateYYYYMMDD(now);
  const id = `brf_${now.getTime()}`;
  const top1 = seed?.top1Symbol ?? "TSLA";
  const criteria = seed?.criteriaLabel ?? "거래량 상위 + 변동률 상위(가중치)";
  const up = Math.random() > 0.45;

  return {
    id,
    date,
    title: `당신이 잠든 사이 — ${date} 브리핑 (수동 생성)`,
    status: "READY",
    top1Symbol: top1,
    criteriaLabel: criteria,
    summaryText: `${top1} 중심으로 거래가 몰리며 아침에 볼 만한 변동성이 나왔습니다.`,
    reportText:
      `1) 오늘의 화제 종목: ${top1}\n- ${criteria}\n- 이슈: (목업) 뉴스 요약 1줄\n\n2) 체크포인트\n- (목업) 이벤트 캘린더 확인\n- (목업) 리스크 관리(분할/손절)`,
    imageDataUrl: makeBriefingCoverSvgDataUrl({
      title: "수동 생성 브리핑",
      subtitle: `${date} • TOP1: ${top1}`,
      accent: up ? "green" : "red",
    }),
    createdAt: now.toISOString(),
  };
}


